      - name: Build JupyterLite site
        run: |
          jupyter lite build \
            --output-dir dist \
            --contents . \
            --federated-extensions \
              jupyterlite_pyodide_kernel
