name: Build and Deploy JupyterLite

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install JupyterLite with Pyodide
        run: |
          pip install \
            jupyterlite \
            jupyterlite-pyodide-kernel

      - name: Build JupyterLite site
        run: |
          jupyter lite build \
            --output-dir dist \
            --contents . \
            --federated-extensions \
              jupyterlite_pyodide_kernel


      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
